BEGIN TRANSACTION;
CREATE TABLE Companies (
   company TEXT NOT NULL,
   stock TEXT NOT NULL
   ); 
Insert Into Companies VALUES("3M","MMM");
Insert Into Companies VALUES("A. O. Smith","AOS");
Insert Into Companies VALUES("Abbott","ABT");
Insert Into Companies VALUES("AbbVie","ABBV");
Insert Into Companies VALUES("Accenture","ACN");
Insert Into Companies VALUES("Adobe.","ADBE");
Insert Into Companies VALUES("Advanced Micro Devices","AMD");
Insert Into Companies VALUES("AES Corporation","AES");
Insert Into Companies VALUES("Aflac","AFL");
Insert Into Companies VALUES("Agilent Technologies","A");
Insert Into Companies VALUES("Air Products and Chemicals","APD");
Insert Into Companies VALUES("Airbnb","ABNB");
Insert Into Companies VALUES("Akamai","AKAM");
Insert Into Companies VALUES("Albemarle Corporation","ALB");
Insert Into Companies VALUES("Alexandria Real Estate Equities","ARE");
Insert Into Companies VALUES("Align Technology","ALGN");
Insert Into Companies VALUES("Allegion","ALLE");
Insert Into Companies VALUES("Alliant Energy","LNT");
Insert Into Companies VALUES("Allstate","ALL");
Insert Into Companies VALUES("Google","GOOGL");
Insert Into Companies VALUES("Altria","MO");
Insert Into Companies VALUES("Amazon","AMZN");
Insert Into Companies VALUES("Amcor","AMCR");
Insert Into Companies VALUES("Ameren","AEE");
Insert Into Companies VALUES("American Airlines Group","AAL");
Insert Into Companies VALUES("American Electric Power","AEP");
Insert Into Companies VALUES("American Express","AXP");
Insert Into Companies VALUES("American International Group","AIG");
Insert Into Companies VALUES("American Tower","AMT");
Insert Into Companies VALUES("American Water Works","AWK");
Insert Into Companies VALUES("Ameriprise Financial","AMP");
Insert Into Companies VALUES("Ametek","AME");
Insert Into Companies VALUES("Amgen","AMGN");
Insert Into Companies VALUES("Amphenol","APH");
Insert Into Companies VALUES("Analog Devices","ADI");
Insert Into Companies VALUES("Ansys","ANSS");
Insert Into Companies VALUES("Aon","AON");
Insert Into Companies VALUES("APA Corporation","APA");
Insert Into Companies VALUES("Apple","AAPL");
Insert Into Companies VALUES("Applied Materials","AMAT");
Insert Into Companies VALUES("Aptiv","APTV");
Insert Into Companies VALUES("Arch Capital Group","ACGL");
Insert Into Companies VALUES("Archer-Daniels-Midland","ADM");
Insert Into Companies VALUES("Arista Networks","ANET");
Insert Into Companies VALUES("Arthur J. Gallagher & Co","AJG");
Insert Into Companies VALUES("Assurant","AIZ");
Insert Into Companies VALUES("AT&T","T");
Insert Into Companies VALUES("Atmos Energy","ATO");
Insert Into Companies VALUES("Autodesk","ADSK");
Insert Into Companies VALUES("Automatic Data Processing","ADP");
Insert Into Companies VALUES("AutoZone","AZO");
Insert Into Companies VALUES("AvalonBay Communities","AVB");
Insert Into Companies VALUES("Avery Dennison","AVY");
Insert Into Companies VALUES("Axon Enterprise","AXON");
Insert Into Companies VALUES("Baker Hughes","BKR");
Insert Into Companies VALUES("Ball Corporation","BALL");
Insert Into Companies VALUES("Bank of America","BAC");
Insert Into Companies VALUES("Bank of New York Mellon","BK");
Insert Into Companies VALUES("Bath & Body Works","BBWI");
Insert Into Companies VALUES("Baxter International","BAX");
Insert Into Companies VALUES("Becton Dickinson","BDX");
Insert Into Companies VALUES("Berkshire Hathaway","BRK.B");
Insert Into Companies VALUES("Best Buy","BBY");
Insert Into Companies VALUES("Bio-Rad","BIO");
Insert Into Companies VALUES("Bio-Techne","TECH");
Insert Into Companies VALUES("Biogen","BIIB");
Insert Into Companies VALUES("BlackRock","BLK");
Insert Into Companies VALUES("Blackstone","BX");
Insert Into Companies VALUES("Boeing","BA");
Insert Into Companies VALUES("Booking Holdings","BKNG");
Insert Into Companies VALUES("BorgWarner","BWA");
Insert Into Companies VALUES("Boston Properties","BXP");
Insert Into Companies VALUES("Boston Scientific","BSX");
Insert Into Companies VALUES("Bristol Myers Squibb","BMY");
Insert Into Companies VALUES("Broadcom","AVGO");
Insert Into Companies VALUES("Broadridge Financial Solutions","BR");
Insert Into Companies VALUES("Brown & Brown","BRO");
Insert Into Companies VALUES("Brown-Forman","BF.B");
Insert Into Companies VALUES("Builders FirstSource","BLDR");
Insert Into Companies VALUES("Bunge Global SA","BG");
Insert Into Companies VALUES("Cadence Design Systems","CDNS");
Insert Into Companies VALUES("Caesars Entertainment","CZR");
Insert Into Companies VALUES("Camden Property Trust","CPT");
Insert Into Companies VALUES("Campbell Soup Company","CPB");
Insert Into Companies VALUES("Capital One","COF");
Insert Into Companies VALUES("Cardinal Health","CAH");
Insert Into Companies VALUES("CarMax","KMX");
Insert Into Companies VALUES("Carnival","CCL");
Insert Into Companies VALUES("Carrier Global","CARR");
Insert Into Companies VALUES("Catalent","CTLT");
Insert Into Companies VALUES("Caterpillar Inc.","CAT");
Insert Into Companies VALUES("Cboe Global Markets","CBOE");
Insert Into Companies VALUES("CBRE Group","CBRE");
Insert Into Companies VALUES("CDW","CDW");
Insert Into Companies VALUES("Celanese","CE");
Insert Into Companies VALUES("Cencora","COR");
Insert Into Companies VALUES("Centene","CNC");
Insert Into Companies VALUES("CenterPoint Energy","CNP");
Insert Into Companies VALUES("CF Industries","CF");
Insert Into Companies VALUES("CH Robinson","CHRW");
Insert Into Companies VALUES("Charles River Laboratories","CRL");
Insert Into Companies VALUES("Charles Schwab","SCHW");
Insert Into Companies VALUES("Charter Communications","CHTR");
Insert Into Companies VALUES("Chevron","CVX");
Insert Into Companies VALUES("Chipotle","CMG");
Insert Into Companies VALUES("Chubb","CB");
Insert Into Companies VALUES("Church & Dwight","CHD");
Insert Into Companies VALUES("Cigna","CI");
Insert Into Companies VALUES("Cincinnati Financial","CINF");
Insert Into Companies VALUES("Cintas","CTAS");
Insert Into Companies VALUES("Cisco","CSCO");
Insert Into Companies VALUES("Citigroup","C");
Insert Into Companies VALUES("Citizens Financial Group","CFG");
Insert Into Companies VALUES("Clorox","CLX");
Insert Into Companies VALUES("CME Group","CME");
Insert Into Companies VALUES("CMS Energy","CMS");
Insert Into Companies VALUES("Coca-Cola","KO");
Insert Into Companies VALUES("Cognizant","CTSH");
Insert Into Companies VALUES("Colgate-Palmolive","CL");
Insert Into Companies VALUES("Comcast","CMCSA");
Insert Into Companies VALUES("Comerica","CMA");
Insert Into Companies VALUES("Conagra Brands","CAG");
Insert Into Companies VALUES("ConocoPhillips","COP");
Insert Into Companies VALUES("Consolidated Edison","ED");
Insert Into Companies VALUES("Constellation Brands","STZ");
Insert Into Companies VALUES("Constellation Energy","CEG");
Insert Into Companies VALUES("CooperCompanies","COO");
Insert Into Companies VALUES("Copart","CPRT");
Insert Into Companies VALUES("Corning Inc.","GLW");
Insert Into Companies VALUES("Corpay","CPAY");
Insert Into Companies VALUES("Corteva","CTVA");
Insert Into Companies VALUES("CoStar Group","CSGP");
Insert Into Companies VALUES("Costco","COST");
Insert Into Companies VALUES("Coterra","CTRA");
Insert Into Companies VALUES("Crown Castle","CCI");
Insert Into Companies VALUES("CSX","CSX");
Insert Into Companies VALUES("Cummins","CMI");
Insert Into Companies VALUES("CVS Health","CVS");
Insert Into Companies VALUES("Danaher Corporation","DHR");
Insert Into Companies VALUES("Darden Restaurants","DRI");
Insert Into Companies VALUES("DaVita Inc.","DVA");
Insert Into Companies VALUES("Dayforce","DAY");
Insert Into Companies VALUES("Deckers Brands","DECK");
Insert Into Companies VALUES("John Deere","DE");
Insert Into Companies VALUES("Delta Air Lines","DAL");
Insert Into Companies VALUES("Devon Energy","DVN");
Insert Into Companies VALUES("Dexcom","DXCM");
Insert Into Companies VALUES("Diamondback Energy","FANG");
Insert Into Companies VALUES("Digital Realty","DLR");
Insert Into Companies VALUES("Discover Financial","DFS");
Insert Into Companies VALUES("Dollar General","DG");
Insert Into Companies VALUES("Dollar Tree","DLTR");
Insert Into Companies VALUES("Dominion Energy","D");
Insert Into Companies VALUES("Domino's","DPZ");
Insert Into Companies VALUES("Dover Corporation","DOV");
Insert Into Companies VALUES("Dow Inc.","DOW");
Insert Into Companies VALUES("DR Horton","DHI");
Insert Into Companies VALUES("DTE Energy","DTE");
Insert Into Companies VALUES("Duke Energy","DUK");
Insert Into Companies VALUES("DuPont","DD");
Insert Into Companies VALUES("Eastman Chemical Company","EMN");
Insert Into Companies VALUES("Eaton Corporation","ETN");
Insert Into Companies VALUES("eBay","EBAY");
Insert Into Companies VALUES("Ecolab","ECL");
Insert Into Companies VALUES("Edison International","EIX");
Insert Into Companies VALUES("Edwards Lifesciences","EW");
Insert Into Companies VALUES("Electronic Arts","EA");
Insert Into Companies VALUES("Elevance Health","ELV");
Insert Into Companies VALUES("Eli Lilly","LLY");
Insert Into Companies VALUES("Emerson Electric","EMR");
Insert Into Companies VALUES("Enphase","ENPH");
Insert Into Companies VALUES("Entergy","ETR");
Insert Into Companies VALUES("EOG Resources","EOG");
Insert Into Companies VALUES("EPAM Systems","EPAM");
Insert Into Companies VALUES("EQT","EQT");
Insert Into Companies VALUES("Equifax","EFX");
Insert Into Companies VALUES("Equinix","EQIX");
Insert Into Companies VALUES("Equity Residential","EQR");
Insert Into Companies VALUES("Essex Property Trust","ESS");
Insert Into Companies VALUES("Estee Lauder","EL");
Insert Into Companies VALUES("Etsy","ETSY");
Insert Into Companies VALUES("Everest Re","EG");
Insert Into Companies VALUES("Evergy","EVRG");
Insert Into Companies VALUES("Eversource","ES");
Insert Into Companies VALUES("Exelon","EXC");
Insert Into Companies VALUES("Expedia Group","EXPE");
Insert Into Companies VALUES("Expeditors International","EXPD");
Insert Into Companies VALUES("Extra Space Storage","EXR");
Insert Into Companies VALUES("ExxonMobil","XOM");
Insert Into Companies VALUES("F5, Inc.","FFIV");
Insert Into Companies VALUES("FactSet","FDS");
Insert Into Companies VALUES("Fair Isaac","FICO");
Insert Into Companies VALUES("Fastenal","FAST");
Insert Into Companies VALUES("Federal Realty","FRT");
Insert Into Companies VALUES("FedEx","FDX");
Insert Into Companies VALUES("Fidelity National Information Services","FIS");
Insert Into Companies VALUES("Fifth Third Bank","FITB");
Insert Into Companies VALUES("First Solar","FSLR");
Insert Into Companies VALUES("FirstEnergy","FE");
Insert Into Companies VALUES("Fiserv","FI");
Insert Into Companies VALUES("FMC Corporation","FMC");
Insert Into Companies VALUES("Ford Motor Company","F");
Insert Into Companies VALUES("Fortinet","FTNT");
Insert Into Companies VALUES("Fortive","FTV");
Insert Into Companies VALUES("Fox Corporation","FOXA");
Insert Into Companies VALUES("Franklin Templeton","BEN");
Insert Into Companies VALUES("Freeport-McMoRan","FCX");
Insert Into Companies VALUES("Garmin","GRMN");
Insert Into Companies VALUES("Gartner","IT");
Insert Into Companies VALUES("GE Aerospace","GE");
Insert Into Companies VALUES("GE HealthCare","GEHC");
Insert Into Companies VALUES("GE Vernova","GEV");
Insert Into Companies VALUES("Gen Digital","GEN");
Insert Into Companies VALUES("Generac","GNRC");
Insert Into Companies VALUES("General Dynamics","GD");
Insert Into Companies VALUES("General Mills","GIS");
Insert Into Companies VALUES("General Motors","GM");
Insert Into Companies VALUES("Genuine Parts Company","GPC");
Insert Into Companies VALUES("Gilead Sciences","GILD");
Insert Into Companies VALUES("Global Payments","GPN");
Insert Into Companies VALUES("Globe Life","GL");
Insert Into Companies VALUES("Goldman Sachs","GS");
Insert Into Companies VALUES("Halliburton","HAL");
Insert Into Companies VALUES("Hartford (The)","HIG");
Insert Into Companies VALUES("Hasbro","HAS");
Insert Into Companies VALUES("HCA Healthcare","HCA");
Insert Into Companies VALUES("Healthpeak","DOC");
Insert Into Companies VALUES("Henry Schein","HSIC");
Insert Into Companies VALUES("Hershey's","HSY");
Insert Into Companies VALUES("Hess Corporation","HES");
Insert Into Companies VALUES("Hewlett Packard Enterprise","HPE");
Insert Into Companies VALUES("Hilton Worldwide","HLT");
Insert Into Companies VALUES("Hologic","HOLX");
Insert Into Companies VALUES("Home Depot","HD");
Insert Into Companies VALUES("Honeywell","HON");
Insert Into Companies VALUES("Hormel Foods","HRL");
Insert Into Companies VALUES("Host Hotels & Resorts","HST");
Insert Into Companies VALUES("Howmet Aerospace","HWM");
Insert Into Companies VALUES("HP","HPQ");
Insert Into Companies VALUES("Hubbell Incorporated","HUBB");
Insert Into Companies VALUES("Humana","HUM");
Insert Into Companies VALUES("Huntington Bancshares","HBAN");
Insert Into Companies VALUES("Huntington Ingalls","HII");
Insert Into Companies VALUES("IBM","IBM");
Insert Into Companies VALUES("IDEX Corporation","IEX");
Insert Into Companies VALUES("Idexx Laboratories","IDXX");
Insert Into Companies VALUES("Illinois Tool Works","ITW");
Insert Into Companies VALUES("Illumina","ILMN");
Insert Into Companies VALUES("Incyte","INCY");
Insert Into Companies VALUES("Ingersoll Rand","IR");
Insert Into Companies VALUES("Insulet","PODD");
Insert Into Companies VALUES("Intel","INTC");
Insert Into Companies VALUES("Intercontinental Exchange","ICE");
Insert Into Companies VALUES("International Flavors & Fragrances","IFF");
Insert Into Companies VALUES("International Paper","IP");
Insert Into Companies VALUES("Interpublic Group of Companies (The)","IPG");
Insert Into Companies VALUES("Intuit","INTU");
Insert Into Companies VALUES("Intuitive Surgical","ISRG");
Insert Into Companies VALUES("Invesco","IVZ");
Insert Into Companies VALUES("Invitation Homes","INVH");
Insert Into Companies VALUES("IQVIA","IQV");
Insert Into Companies VALUES("Iron Mountain","IRM");
Insert Into Companies VALUES("J.B. Hunt","JBHT");
Insert Into Companies VALUES("Jabil","JBL");
Insert Into Companies VALUES("Jack Henry","JKHY");
Insert Into Companies VALUES("Jacobs Solutions","J");
Insert Into Companies VALUES("Johnson & Johnson","JNJ");
Insert Into Companies VALUES("Johnson Controls","JCI");
Insert Into Companies VALUES("JPMorgan Chase","JPM");
Insert Into Companies VALUES("Juniper Networks","JNPR");
Insert Into Companies VALUES("Kellanova","K");
Insert Into Companies VALUES("Kenvue","KVUE");
Insert Into Companies VALUES("Keurig Dr Pepper","KDP");
Insert Into Companies VALUES("KeyCorp","KEY");
Insert Into Companies VALUES("Keysight","KEYS");
Insert Into Companies VALUES("Kimberly-Clark","KMB");
Insert Into Companies VALUES("Kimco Realty","KIM");
Insert Into Companies VALUES("Kinder Morgan","KMI");
Insert Into Companies VALUES("KLA Corporation","KLAC");
Insert Into Companies VALUES("Kraft Heinz","KHC");
Insert Into Companies VALUES("Kroger","KR");
Insert Into Companies VALUES("L3Harris","LHX");
Insert Into Companies VALUES("LabCorp","LH");
Insert Into Companies VALUES("Lam Research","LRCX");
Insert Into Companies VALUES("Lamb Weston","LW");
Insert Into Companies VALUES("Las Vegas Sands","LVS");
Insert Into Companies VALUES("Leidos","LDOS");
Insert Into Companies VALUES("Lennar","LEN");
Insert Into Companies VALUES("Linde plc","LIN");
Insert Into Companies VALUES("Live Nation Entertainment","LYV");
Insert Into Companies VALUES("LKQ Corporation","LKQ");
Insert Into Companies VALUES("Lockheed Martin","LMT");
Insert Into Companies VALUES("Loews Corporation","L");
Insert Into Companies VALUES("Lowe's","LOW");
Insert Into Companies VALUES("Lululemon Athletica","LULU");
Insert Into Companies VALUES("LyondellBasell","LYB");
Insert Into Companies VALUES("M&T Bank","MTB");
Insert Into Companies VALUES("Marathon Oil","MRO");
Insert Into Companies VALUES("Marathon Petroleum","MPC");
Insert Into Companies VALUES("MarketAxess","MKTX");
Insert Into Companies VALUES("Marriott International","MAR");
Insert Into Companies VALUES("Marsh McLennan","MMC");
Insert Into Companies VALUES("Martin Marietta Materials","MLM");
Insert Into Companies VALUES("Masco","MAS");
Insert Into Companies VALUES("Mastercard","MA");
Insert Into Companies VALUES("Match Group","MTCH");
Insert Into Companies VALUES("McCormick & Company","MKC");
Insert Into Companies VALUES("McDonald's","MCD");
Insert Into Companies VALUES("McKesson","MCK");
Insert Into Companies VALUES("Medtronic","MDT");
Insert Into Companies VALUES("Merck & Co.","MRK");
Insert Into Companies VALUES("Meta Platforms","META");
Insert Into Companies VALUES("MetLife","MET");
Insert Into Companies VALUES("Mettler Toledo","MTD");
Insert Into Companies VALUES("MGM Resorts","MGM");
Insert Into Companies VALUES("Microchip Technology","MCHP");
Insert Into Companies VALUES("Micron Technology","MU");
Insert Into Companies VALUES("Microsoft","MSFT");
Insert Into Companies VALUES("Mid-America Apartment Communities","MAA");
Insert Into Companies VALUES("Moderna","MRNA");
Insert Into Companies VALUES("Mohawk Industries","MHK");
Insert Into Companies VALUES("Molina Healthcare","MOH");
Insert Into Companies VALUES("Molson Coors Beverage Company","TAP");
Insert Into Companies VALUES("Mondelez International","MDLZ");
Insert Into Companies VALUES("Monolithic Power Systems","MPWR");
Insert Into Companies VALUES("Monster Beverage","MNST");
Insert Into Companies VALUES("Moody's Corporation","MCO");
Insert Into Companies VALUES("Morgan Stanley","MS");
Insert Into Companies VALUES("Mosaic Company (The)","MOS");
Insert Into Companies VALUES("Motorola Solutions","MSI");
Insert Into Companies VALUES("MSCI","MSCI");
Insert Into Companies VALUES("Nasdaq, Inc.","NDAQ");
Insert Into Companies VALUES("NetApp","NTAP");
Insert Into Companies VALUES("Netflix","NFLX");
Insert Into Companies VALUES("Newmont","NEM");
Insert Into Companies VALUES("News Corp","NWSA");
Insert Into Companies VALUES("NextEra Energy","NEE");
Insert Into Companies VALUES("Nike, Inc.","NKE");
Insert Into Companies VALUES("NiSource","NI");
Insert Into Companies VALUES("Nordson Corporation","NDSN");
Insert Into Companies VALUES("Norfolk Southern Railway","NSC");
Insert Into Companies VALUES("Northern Trust","NTRS");
Insert Into Companies VALUES("Northrop Grumman","NOC");
Insert Into Companies VALUES("Norwegian Cruise Line Holdings","NCLH");
Insert Into Companies VALUES("NRG Energy","NRG");
Insert Into Companies VALUES("Nucor","NUE");
Insert Into Companies VALUES("Nvidia","NVDA");
Insert Into Companies VALUES("NVR, Inc.","NVR");
Insert Into Companies VALUES("NXP Semiconductors","NXPI");
Insert Into Companies VALUES("O'Reilly Auto Parts","ORLY");
Insert Into Companies VALUES("Occidental Petroleum","OXY");
Insert Into Companies VALUES("Old Dominion","ODFL");
Insert Into Companies VALUES("Omnicom Group","OMC");
Insert Into Companies VALUES("ON Semiconductor","ON");
Insert Into Companies VALUES("ONEOK","OKE");
Insert Into Companies VALUES("Oracle Corporation","ORCL");
Insert Into Companies VALUES("Otis Worldwide","OTIS");
Insert Into Companies VALUES("Paccar","PCAR");
Insert Into Companies VALUES("Packaging Corporation of America","PKG");
Insert Into Companies VALUES("Palo Alto Networks","PANW");
Insert Into Companies VALUES("Paramount Global","PARA");
Insert Into Companies VALUES("Parker Hannifin","PH");
Insert Into Companies VALUES("Paychex","PAYX");
Insert Into Companies VALUES("Paycom","PAYC");
Insert Into Companies VALUES("PayPal","PYPL");
Insert Into Companies VALUES("Pentair","PNR");
Insert Into Companies VALUES("PepsiCo","PEP");
Insert Into Companies VALUES("Pfizer","PFE");
Insert Into Companies VALUES("PG&E Corporation","PCG");
Insert Into Companies VALUES("Philip Morris International","PM");
Insert Into Companies VALUES("Phillips 66","PSX");
Insert Into Companies VALUES("Pinnacle West","PNW");
Insert Into Companies VALUES("Pioneer Natural Resources","PXD");
Insert Into Companies VALUES("PNC Financial Services","PNC");
Insert Into Companies VALUES("Pool Corporation","POOL");
Insert Into Companies VALUES("PPG Industries","PPG");
Insert Into Companies VALUES("PPL Corporation","PPL");
Insert Into Companies VALUES("Principal Financial Group","PFG");
Insert Into Companies VALUES("Procter & Gamble","PG");
Insert Into Companies VALUES("Progressive Corporation","PGR");
Insert Into Companies VALUES("Prologis","PLD");
Insert Into Companies VALUES("Prudential Financial","PRU");
Insert Into Companies VALUES("Public Service Enterprise Group","PEG");
Insert Into Companies VALUES("PTC","PTC");
Insert Into Companies VALUES("Public Storage","PSA");
Insert Into Companies VALUES("PulteGroup","PHM");
Insert Into Companies VALUES("Qorvo","QRVO");
Insert Into Companies VALUES("Quanta Services","PWR");
Insert Into Companies VALUES("Qualcomm","QCOM");
Insert Into Companies VALUES("Quest Diagnostics","DGX");
Insert Into Companies VALUES("Ralph Lauren Corporation","RL");
Insert Into Companies VALUES("Raymond James","RJF");
Insert Into Companies VALUES("RTX Corporation","RTX");
Insert Into Companies VALUES("Realty Income","O");
Insert Into Companies VALUES("Regency Centers","REG");
Insert Into Companies VALUES("Regeneron","REGN");
Insert Into Companies VALUES("Regions Financial Corporation","RF");
Insert Into Companies VALUES("Republic Services","RSG");
Insert Into Companies VALUES("ResMed","RMD");
Insert Into Companies VALUES("Revvity","RVTY");
Insert Into Companies VALUES("Robert Half","RHI");
Insert Into Companies VALUES("Rockwell Automation","ROK");
Insert Into Companies VALUES("Rollins, Inc.","ROL");
Insert Into Companies VALUES("Roper Technologies","ROP");
Insert Into Companies VALUES("Ross Stores","ROST");
Insert Into Companies VALUES("Royal Caribbean","RCL");
Insert Into Companies VALUES("S&P Global","SPGI");
Insert Into Companies VALUES("Salesforce","CRM");
Insert Into Companies VALUES("SBA Communications","SBAC");
Insert Into Companies VALUES("Schlumberger","SLB");
Insert Into Companies VALUES("Seagate Technology","STX");
Insert Into Companies VALUES("Sempra Energy","SRE");
Insert Into Companies VALUES("ServiceNow","NOW");
Insert Into Companies VALUES("Sherwin-Williams","SHW");
Insert Into Companies VALUES("Simon Property Group","SPG");
Insert Into Companies VALUES("Skyworks Solutions","SWKS");
Insert Into Companies VALUES("J.M. Smucker","SJM");
Insert Into Companies VALUES("Snap-on","SNA");
Insert Into Companies VALUES("Solventum","SOLV");
Insert Into Companies VALUES("Southern Company","SO");
Insert Into Companies VALUES("Southwest Airlines","LUV");
Insert Into Companies VALUES("Stanley Black & Decker","SWK");
Insert Into Companies VALUES("Starbucks","SBUX");
Insert Into Companies VALUES("State Street Corporation","STT");
Insert Into Companies VALUES("Steel Dynamics","STLD");
Insert Into Companies VALUES("Steris","STE");
Insert Into Companies VALUES("Stryker Corporation","SYK");
Insert Into Companies VALUES("Supermicro","SMCI");
Insert Into Companies VALUES("Synchrony Financial","SYF");
Insert Into Companies VALUES("Synopsys","SNPS");
Insert Into Companies VALUES("Sysco","SYY");
Insert Into Companies VALUES("T-Mobile","TMUS");
Insert Into Companies VALUES("T. Rowe Price","TROW");
Insert Into Companies VALUES("Take-Two Interactive","TTWO");
Insert Into Companies VALUES("Tapestry","TPR");
Insert Into Companies VALUES("Targa Resources","TRGP");
Insert Into Companies VALUES("Target Corporation","TGT");
Insert Into Companies VALUES("TE Connectivity","TEL");
Insert Into Companies VALUES("Teledyne","TDY");
Insert Into Companies VALUES("Teleflex","TFX");
Insert Into Companies VALUES("Teradyne","TER");
Insert Into Companies VALUES("Tesla","TSLA");
Insert Into Companies VALUES("Texas Instruments","TXN");
Insert Into Companies VALUES("Textron","TXT");
Insert Into Companies VALUES("Thermo Fisher Scientific","TMO");
Insert Into Companies VALUES("TJX Companies","TJX");
Insert Into Companies VALUES("Tractor Supply","TSCO");
Insert Into Companies VALUES("Trane Technologies","TT");
Insert Into Companies VALUES("TransDigm Group","TDG");
Insert Into Companies VALUES("Travelers Companies","TRV");
Insert Into Companies VALUES("Trimble","TRMB");
Insert Into Companies VALUES("Truist","TFC");
Insert Into Companies VALUES("Tyler Technologies","TYL");
Insert Into Companies VALUES("Tyson Foods","TSN");
Insert Into Companies VALUES("U.S. Bank","USB");
Insert Into Companies VALUES("Uber","UBER");
Insert Into Companies VALUES("UDR","UDR");
Insert Into Companies VALUES("Ulta Beauty","ULTA");
Insert Into Companies VALUES("Union Pacific Corporation","UNP");
Insert Into Companies VALUES("United Airlines Holdings","UAL");
Insert Into Companies VALUES("United Parcel Service","UPS");
Insert Into Companies VALUES("United Rentals","URI");
Insert Into Companies VALUES("UnitedHealth Group","UNH");
Insert Into Companies VALUES("Universal Health Services","UHS");
Insert Into Companies VALUES("Valero Energy","VLO");
Insert Into Companies VALUES("Ventas","VTR");
Insert Into Companies VALUES("Veralto","VLTO");
Insert Into Companies VALUES("Verisign","VRSN");
Insert Into Companies VALUES("Verisk","VRSK");
Insert Into Companies VALUES("Verizon","VZ");
Insert Into Companies VALUES("Vertex Pharmaceuticals","VRTX");
Insert Into Companies VALUES("Viatris","VTRS");
Insert Into Companies VALUES("Vici Properties","VICI");
Insert Into Companies VALUES("Visa Inc.","V");
Insert Into Companies VALUES("Vulcan Materials Company","VMC");
Insert Into Companies VALUES("Berkley","WRB");
Insert Into Companies VALUES("Wabtec","WAB");
Insert Into Companies VALUES("Walgreens Boots Alliance","WBA");
Insert Into Companies VALUES("Walmart","WMT");
Insert Into Companies VALUES("Walt Disney","DIS");
Insert Into Companies VALUES("Warner Bros. Discovery","WBD");
Insert Into Companies VALUES("Waste Management","WM");
Insert Into Companies VALUES("Waters Corporation","WAT");
Insert Into Companies VALUES("WEC Energy Group","WEC");
Insert Into Companies VALUES("Wells Fargo","WFC");
Insert Into Companies VALUES("Welltower","WELL");
Insert Into Companies VALUES("West Pharmaceutical Services","WST");
Insert Into Companies VALUES("Western Digital","WDC");
Insert Into Companies VALUES("WestRock","WRK");
Insert Into Companies VALUES("Weyerhaeuser","WY");
Insert Into Companies VALUES("Williams Companies","WMB");
Insert Into Companies VALUES("Willis Towers Watson","WTW");
Insert Into Companies VALUES("W. W. Grainger","GWW");
Insert Into Companies VALUES("Wynn Resorts","WYNN");
Insert Into Companies VALUES("Xcel Energy","XEL");
Insert Into Companies VALUES("Xylem Inc.","XYL");
Insert Into Companies VALUES("Yum! Brands","YUM");
Insert Into Companies VALUES("Zebra Technologies","ZBRA");
Insert Into Companies VALUES("Zimmer Biomet","ZBH");
Insert Into Companies VALUES("Zoetis","ZTS");
create Table Searchterms(
   company text NOT NULL,
   searchterm text not null,
   FOREIGN KEY (company)
       REFERENCES Companies (company) 
);
create Table stockvalue(
   stock text NOT NULL,
   stockYear INTEGER not null,
   stockMonth INTEGER not null,
   stockDay INTEGER not null,
   stockHour INTEGER not null,
   stockminute INTEGER not null,
   stockvalue real not null,
    FOREIGN KEY (stock)
       REFERENCES Companies (stock) 
   ); 
create Table Urls(
   storyUrl text NOT NULL,
   company text not null,
   headline text not null,
   storyYear INTEGER not null,
   storyMonth INTEGER not null,
   storyDay INTEGER not null,
   storyHour INTEGER not null,
   storyminute INTEGER not null,
    FOREIGN KEY (company)
       REFERENCES Companies (company) 
   ); 
create table CleanedStories(
   storyUrl text NOT NULL,
   Cleanedbody text not null,
   FOREIGN KEY(storyUrl)
   REFERENCES Urls (storyUrl)
);
create table storySentiment(
   Cleanedbody text not null,
   pos real not null,
   neg real not null,
   overall real not null,
   FOREIGN KEY(Cleanedbody)
   REFERENCES CleanedStories (Cleanedbody)
);
create table PossibleStockTimes(
   posHour int Not Null,
   posMin int not null
);
insert into PossibleStockTimes values(9,30);
insert into PossibleStockTimes values(9,45);
insert into PossibleStockTimes values(10,0);
insert into PossibleStockTimes values(10,15);
insert into PossibleStockTimes values(10,30);
insert into PossibleStockTimes values(10,45);
insert into PossibleStockTimes values(11,0);
insert into PossibleStockTimes values(11,15);
insert into PossibleStockTimes values(11,30);
insert into PossibleStockTimes values(11,45);
insert into PossibleStockTimes values(12,0);
insert into PossibleStockTimes values(12,15);
insert into PossibleStockTimes values(12,30);
insert into PossibleStockTimes values(12,45);
insert into PossibleStockTimes values(13,0);
insert into PossibleStockTimes values(13,15);
insert into PossibleStockTimes values(13,30);
insert into PossibleStockTimes values(13,45);
insert into PossibleStockTimes values(14,0);
insert into PossibleStockTimes values(14,15);
insert into PossibleStockTimes values(14,30);
insert into PossibleStockTimes values(14,45);
insert into PossibleStockTimes values(15,0);
insert into PossibleStockTimes values(15,15);
insert into PossibleStockTimes values(15,30);
insert into PossibleStockTimes values(15,45);
COMMIT;